/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module \$paramod\DFF\N=16 (clk, reset, data_in, data_delayed);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input clk;
  output [15:0] data_delayed;
  input [15:0] data_in;
  input reset;
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(reset),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(reset),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(reset),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(reset),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(reset),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(reset),
    .Y(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(reset),
    .Y(_10_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(reset),
    .Y(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(reset),
    .Y(_12_)
  );
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(reset),
    .Y(_13_)
  );
  sky130_fd_sc_hd__clkinv_1 _30_ (
    .A(reset),
    .Y(_14_)
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(reset),
    .Y(_15_)
  );
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clk),
    .D(data_in[0]),
    .Q(data_delayed[0]),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(data_in[1]),
    .Q(data_delayed[1]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(data_in[2]),
    .Q(data_delayed[2]),
    .RESET_B(_02_)
  );
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(data_in[3]),
    .Q(data_delayed[3]),
    .RESET_B(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(data_in[4]),
    .Q(data_delayed[4]),
    .RESET_B(_04_)
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(data_in[5]),
    .Q(data_delayed[5]),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(data_in[6]),
    .Q(data_delayed[6]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(data_in[7]),
    .Q(data_delayed[7]),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(data_in[8]),
    .Q(data_delayed[8]),
    .RESET_B(_08_)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(clk),
    .D(data_in[9]),
    .Q(data_delayed[9]),
    .RESET_B(_09_)
  );
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(clk),
    .D(data_in[10]),
    .Q(data_delayed[10]),
    .RESET_B(_10_)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(clk),
    .D(data_in[11]),
    .Q(data_delayed[11]),
    .RESET_B(_11_)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(data_in[12]),
    .Q(data_delayed[12]),
    .RESET_B(_12_)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(data_in[13]),
    .Q(data_delayed[13]),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(data_in[14]),
    .Q(data_delayed[14]),
    .RESET_B(_14_)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(data_in[15]),
    .Q(data_delayed[15]),
    .RESET_B(_15_)
  );
endmodule

module FIR_Filters(clk, reset, data_in, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  input clk;
  input [15:0] data_in;
  output [15:0] data_out;
  input reset;
  wire [22:0] sum;
  wire [15:0] \x[1] ;
  wire [15:0] \x[2] ;
  wire [15:0] \x[3] ;
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(\x[3] [0]),
    .B(data_in[0]),
    .Y(_316_)
  );
  sky130_fd_sc_hd__nor2_1 _319_ (
    .A(\x[3] [1]),
    .B(data_in[1]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xor2_1 _320_ (
    .A(\x[3] [1]),
    .B(data_in[1]),
    .X(_017_)
  );
  sky130_fd_sc_hd__and2_0 _321_ (
    .A(_316_),
    .B(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(\x[1] [0]),
    .B(\x[2] [0]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _323_ (
    .A(\x[1] [1]),
    .B(\x[2] [1]),
    .X(_020_)
  );
  sky130_fd_sc_hd__or2_0 _324_ (
    .A(_316_),
    .B(_017_),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(_019_),
    .B(_020_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(_019_),
    .B(_020_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nand3b_1 _327_ (
    .A_N(_018_),
    .B(_021_),
    .C(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a22o_1 _328_ (
    .A1(\x[3] [0]),
    .A2(data_in[0]),
    .B1(\x[1] [0]),
    .B2(\x[2] [0]),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _329_ (
    .A(_316_),
    .B(_019_),
    .C(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o211ai_1 _330_ (
    .A1(_017_),
    .A2(_020_),
    .B1(_024_),
    .C1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(\x[1] [2]),
    .B(_022_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xnor2_1 _332_ (
    .A(\x[1] [2]),
    .B(_022_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _333_ (
    .A1(_021_),
    .A2(_023_),
    .B1(_018_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2b_1 _334_ (
    .A(\x[3] [2]),
    .B_N(data_in[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _335_ (
    .A(\x[3] [2]),
    .B(data_in[2]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _336_ (
    .A(_016_),
    .B(_032_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _337_ (
    .A(\x[1] [1]),
    .B(\x[2] [1]),
    .C(\x[2] [2]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o21a_1 _338_ (
    .A1(\x[1] [1]),
    .A2(\x[2] [1]),
    .B1(\x[2] [2]),
    .X(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _340_ (
    .A(_033_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xnor3_1 _341_ (
    .A(_029_),
    .B(_030_),
    .C(_037_),
    .X(_038_)
  );
  sky130_fd_sc_hd__nand2b_1 _342_ (
    .A_N(_027_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xnor2_1 _343_ (
    .A(_027_),
    .B(_038_),
    .Y(sum[7])
  );
  sky130_fd_sc_hd__maj3_1 _344_ (
    .A(_029_),
    .B(_030_),
    .C(_037_),
    .X(_040_)
  );
  sky130_fd_sc_hd__maj3_1 _345_ (
    .A(_016_),
    .B(_032_),
    .C(_036_),
    .X(_041_)
  );
  sky130_fd_sc_hd__xnor3_1 _346_ (
    .A(data_in[2]),
    .B(data_in[3]),
    .C(\x[3] [3]),
    .X(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _347_ (
    .A(_031_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _348_ (
    .A(\x[1] [3]),
    .B(\x[2] [3]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__xor2_1 _349_ (
    .A(\x[1] [3]),
    .B(\x[2] [3]),
    .X(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _350_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xor3_1 _351_ (
    .A(_034_),
    .B(_041_),
    .C(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2b_1 _352_ (
    .A(_040_),
    .B_N(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2b_1 _353_ (
    .A_N(_047_),
    .B(_040_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xnor3_1 _354_ (
    .A(_028_),
    .B(_040_),
    .C(_047_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor2b_1 _355_ (
    .A(_039_),
    .B_N(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21o_1 _356_ (
    .A1(_028_),
    .A2(_049_),
    .B1(_048_),
    .X(_052_)
  );
  sky130_fd_sc_hd__maj3_1 _357_ (
    .A(_034_),
    .B(_041_),
    .C(_046_),
    .X(_053_)
  );
  sky130_fd_sc_hd__maj3_1 _358_ (
    .A(_031_),
    .B(_042_),
    .C(_045_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xor2_1 _359_ (
    .A(\x[1] [4]),
    .B(\x[2] [4]),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _360_ (
    .A(_044_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _361_ (
    .A(_044_),
    .B(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__maj3_1 _362_ (
    .A(data_in[2]),
    .B(data_in[3]),
    .C(\x[3] [3]),
    .X(_058_)
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(\x[3] [4]),
    .B(data_in[4]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xor2_1 _364_ (
    .A(_058_),
    .B(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _365_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(_054_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__xor2_1 _367_ (
    .A(_054_),
    .B(_061_),
    .X(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(_053_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _369_ (
    .A(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _370_ (
    .A(_053_),
    .B(_063_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _371_ (
    .A(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _372_ (
    .A(_052_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _373_ (
    .A(_051_),
    .B(_068_),
    .Y(sum[9])
  );
  sky130_fd_sc_hd__maj3_1 _374_ (
    .A(_051_),
    .B(_052_),
    .C(_067_),
    .X(_069_)
  );
  sky130_fd_sc_hd__maj3_1 _375_ (
    .A(_057_),
    .B(_058_),
    .C(_059_),
    .X(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _376_ (
    .A(\x[1] [5]),
    .B(\x[2] [5]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or3_1 _377_ (
    .A(\x[1] [4]),
    .B(\x[2] [4]),
    .C(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__o21ai_0 _378_ (
    .A1(\x[1] [4]),
    .A2(\x[2] [4]),
    .B1(_071_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _380_ (
    .A(\x[3] [5]),
    .B(data_in[5]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__or3_1 _381_ (
    .A(\x[3] [4]),
    .B(data_in[4]),
    .C(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _382_ (
    .A1(\x[3] [4]),
    .A2(data_in[4]),
    .B1(_075_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _383_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _384_ (
    .A(_074_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__xnor2_1 _385_ (
    .A(_070_),
    .B(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _386_ (
    .A(_056_),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(_062_),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _388_ (
    .A(_062_),
    .B(_081_),
    .X(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(_065_),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _390_ (
    .A(_069_),
    .B(_084_),
    .Y(sum[10])
  );
  sky130_fd_sc_hd__maj3_1 _391_ (
    .A(_065_),
    .B(_069_),
    .C(_083_),
    .X(_085_)
  );
  sky130_fd_sc_hd__maj3_1 _392_ (
    .A(_056_),
    .B(_070_),
    .C(_079_),
    .X(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _393_ (
    .A1(_074_),
    .A2(_078_),
    .B1(_076_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _394_ (
    .A(\x[1] [6]),
    .B(\x[2] [6]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor3_1 _395_ (
    .A(\x[1] [5]),
    .B(\x[2] [5]),
    .C(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21ai_0 _396_ (
    .A1(\x[1] [5]),
    .A2(\x[2] [5]),
    .B1(_088_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2b_1 _397_ (
    .A_N(_089_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _398_ (
    .A(\x[3] [6]),
    .B(data_in[6]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor3_1 _399_ (
    .A(\x[3] [5]),
    .B(data_in[5]),
    .C(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _400_ (
    .A1(\x[3] [5]),
    .A2(data_in[5]),
    .B1(_092_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2b_1 _401_ (
    .A_N(_093_),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xor2_1 _402_ (
    .A(_091_),
    .B(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(_087_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xnor2_1 _404_ (
    .A(_087_),
    .B(_096_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _405_ (
    .A(_072_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(_086_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _407_ (
    .A(_086_),
    .B(_099_),
    .X(_101_)
  );
  sky130_fd_sc_hd__xnor2_1 _408_ (
    .A(_082_),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__xnor2_1 _409_ (
    .A(_085_),
    .B(_102_),
    .Y(sum[11])
  );
  sky130_fd_sc_hd__maj3_1 _410_ (
    .A(_082_),
    .B(_085_),
    .C(_101_),
    .X(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _411_ (
    .A1(_072_),
    .A2(_098_),
    .B1(_097_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21bai_1 _412_ (
    .A1(_091_),
    .A2(_095_),
    .B1_N(_093_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _413_ (
    .A(\x[1] [7]),
    .B(\x[2] [7]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xnor2_1 _414_ (
    .A(\x[1] [7]),
    .B(\x[2] [7]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor3_1 _415_ (
    .A(\x[1] [6]),
    .B(\x[2] [6]),
    .C(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_0 _416_ (
    .A1(\x[1] [6]),
    .A2(\x[2] [6]),
    .B1(_107_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2b_1 _417_ (
    .A_N(_108_),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _418_ (
    .A(\x[3] [7]),
    .B(data_in[7]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xnor2_1 _419_ (
    .A(\x[3] [7]),
    .B(data_in[7]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor3_1 _420_ (
    .A(\x[3] [6]),
    .B(data_in[6]),
    .C(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o21ai_0 _421_ (
    .A1(\x[3] [6]),
    .A2(data_in[6]),
    .B1(_112_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2b_1 _422_ (
    .A_N(_113_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__xor2_1 _423_ (
    .A(_110_),
    .B(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__xor2_1 _424_ (
    .A(_105_),
    .B(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _425_ (
    .A(_089_),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2b_1 _426_ (
    .A_N(_118_),
    .B(_104_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _427_ (
    .A(_104_),
    .B(_118_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__and2_0 _428_ (
    .A(_100_),
    .B(_120_),
    .X(_121_)
  );
  sky130_fd_sc_hd__or2_0 _429_ (
    .A(_100_),
    .B(_120_),
    .X(_122_)
  );
  sky130_fd_sc_hd__nand2b_1 _430_ (
    .A_N(_121_),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _431_ (
    .A(_103_),
    .B(_123_),
    .Y(sum[12])
  );
  sky130_fd_sc_hd__a21oi_1 _432_ (
    .A1(_103_),
    .A2(_122_),
    .B1(_121_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__maj3_1 _433_ (
    .A(_089_),
    .B(_105_),
    .C(_116_),
    .X(_125_)
  );
  sky130_fd_sc_hd__o21bai_1 _434_ (
    .A1(_110_),
    .A2(_115_),
    .B1_N(_113_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _435_ (
    .A(\x[1] [8]),
    .B(\x[2] [8]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor3_1 _436_ (
    .A(\x[1] [7]),
    .B(\x[2] [7]),
    .C(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xor2_1 _437_ (
    .A(_106_),
    .B(_127_),
    .X(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _438_ (
    .A(\x[3] [8]),
    .B(data_in[8]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor3_1 _439_ (
    .A(\x[3] [7]),
    .B(data_in[7]),
    .C(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xor2_1 _440_ (
    .A(_111_),
    .B(_130_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _441_ (
    .A(_129_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xor2_1 _442_ (
    .A(_129_),
    .B(_132_),
    .X(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _443_ (
    .A(_126_),
    .B(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _444_ (
    .A(_108_),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2b_1 _445_ (
    .A_N(_136_),
    .B(_125_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xor2_1 _446_ (
    .A(_125_),
    .B(_136_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _447_ (
    .A(_119_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__clkinv_1 _448_ (
    .A(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__or2_0 _449_ (
    .A(_119_),
    .B(_138_),
    .X(_141_)
  );
  sky130_fd_sc_hd__clkinv_1 _450_ (
    .A(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(_139_),
    .B(_141_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xor2_1 _452_ (
    .A(_124_),
    .B(_143_),
    .X(sum[13])
  );
  sky130_fd_sc_hd__maj3_1 _453_ (
    .A(_108_),
    .B(_126_),
    .C(_134_),
    .X(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _454_ (
    .A(_131_),
    .B(_133_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__clkinv_1 _455_ (
    .A(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__xnor2_1 _456_ (
    .A(\x[1] [9]),
    .B(\x[2] [9]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor3_1 _457_ (
    .A(\x[1] [8]),
    .B(\x[2] [8]),
    .C(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_0 _458_ (
    .A1(\x[1] [8]),
    .A2(\x[2] [8]),
    .B1(_147_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2b_1 _459_ (
    .A_N(_148_),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__xnor2_1 _460_ (
    .A(\x[3] [9]),
    .B(data_in[9]),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor3_1 _461_ (
    .A(\x[3] [8]),
    .B(data_in[8]),
    .C(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _462_ (
    .A1(\x[3] [8]),
    .A2(data_in[8]),
    .B1(_151_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2b_1 _463_ (
    .A_N(_152_),
    .B(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _464_ (
    .A(_150_),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__xor2_1 _465_ (
    .A(_150_),
    .B(_154_),
    .X(_156_)
  );
  sky130_fd_sc_hd__xnor2_1 _466_ (
    .A(_145_),
    .B(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _467_ (
    .A(_128_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2b_1 _468_ (
    .A_N(_158_),
    .B(_144_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xor2_1 _469_ (
    .A(_144_),
    .B(_158_),
    .X(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _470_ (
    .A(_137_),
    .B(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__clkinv_1 _471_ (
    .A(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _472_ (
    .A(_137_),
    .B(_160_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(_162_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a211oi_1 _474_ (
    .A1(_103_),
    .A2(_122_),
    .B1(_142_),
    .C1(_121_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor3_1 _475_ (
    .A(_140_),
    .B(_164_),
    .C(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o21ai_0 _476_ (
    .A1(_140_),
    .A2(_165_),
    .B1(_164_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor2b_1 _477_ (
    .A(_166_),
    .B_N(_167_),
    .Y(sum[14])
  );
  sky130_fd_sc_hd__nor2_1 _478_ (
    .A(_161_),
    .B(_166_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__maj3_1 _479_ (
    .A(_128_),
    .B(_146_),
    .C(_156_),
    .X(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _480_ (
    .A(_152_),
    .B(_155_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__clkinv_1 _481_ (
    .A(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xnor2_1 _482_ (
    .A(\x[1] [10]),
    .B(\x[2] [10]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor3_1 _483_ (
    .A(\x[1] [9]),
    .B(\x[2] [9]),
    .C(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o21ai_0 _484_ (
    .A1(\x[1] [9]),
    .A2(\x[2] [9]),
    .B1(_172_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2b_1 _485_ (
    .A_N(_173_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__xnor2_1 _486_ (
    .A(\x[3] [10]),
    .B(data_in[10]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor3_1 _487_ (
    .A(\x[3] [9]),
    .B(data_in[9]),
    .C(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__o21ai_0 _488_ (
    .A1(\x[3] [9]),
    .A2(data_in[9]),
    .B1(_176_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2b_1 _489_ (
    .A_N(_177_),
    .B(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _490_ (
    .A(_175_),
    .B(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xor2_1 _491_ (
    .A(_175_),
    .B(_179_),
    .X(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _492_ (
    .A(_170_),
    .B(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xnor2_1 _493_ (
    .A(_148_),
    .B(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand2b_1 _494_ (
    .A_N(_183_),
    .B(_169_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__xor2_1 _495_ (
    .A(_169_),
    .B(_183_),
    .X(_185_)
  );
  sky130_fd_sc_hd__or2_0 _496_ (
    .A(_159_),
    .B(_185_),
    .X(_186_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(_159_),
    .B(_185_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(_186_),
    .B(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__xor2_1 _499_ (
    .A(_168_),
    .B(_188_),
    .X(sum[15])
  );
  sky130_fd_sc_hd__maj3_1 _500_ (
    .A(_148_),
    .B(_171_),
    .C(_181_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(_177_),
    .B(_180_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__clkinv_1 _502_ (
    .A(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__xnor2_1 _503_ (
    .A(\x[1] [11]),
    .B(\x[2] [11]),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nor3_1 _504_ (
    .A(\x[1] [10]),
    .B(\x[2] [10]),
    .C(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o21ai_0 _505_ (
    .A1(\x[1] [10]),
    .A2(\x[2] [10]),
    .B1(_192_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand2b_1 _506_ (
    .A_N(_193_),
    .B(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__xnor2_1 _507_ (
    .A(\x[3] [11]),
    .B(data_in[11]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor3_1 _508_ (
    .A(\x[3] [10]),
    .B(data_in[10]),
    .C(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o21ai_0 _509_ (
    .A1(\x[3] [10]),
    .A2(data_in[10]),
    .B1(_196_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand2b_1 _510_ (
    .A_N(_197_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nor2_1 _511_ (
    .A(_195_),
    .B(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__xor2_1 _512_ (
    .A(_195_),
    .B(_199_),
    .X(_201_)
  );
  sky130_fd_sc_hd__xnor2_1 _513_ (
    .A(_190_),
    .B(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__xnor2_1 _514_ (
    .A(_173_),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nor2b_1 _515_ (
    .A(_203_),
    .B_N(_189_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xor2_1 _516_ (
    .A(_189_),
    .B(_203_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _517_ (
    .A(_184_),
    .B(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__xor2_1 _518_ (
    .A(_184_),
    .B(_205_),
    .X(_207_)
  );
  sky130_fd_sc_hd__o311ai_0 _519_ (
    .A1(_140_),
    .A2(_164_),
    .A3(_165_),
    .B1(_186_),
    .C1(_162_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _520_ (
    .A1(_168_),
    .A2(_188_),
    .B1(_186_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__xor2_1 _521_ (
    .A(_207_),
    .B(_209_),
    .X(sum[16])
  );
  sky130_fd_sc_hd__a31oi_1 _522_ (
    .A1(_187_),
    .A2(_207_),
    .A3(_208_),
    .B1(_206_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__maj3_1 _523_ (
    .A(_173_),
    .B(_191_),
    .C(_201_),
    .X(_211_)
  );
  sky130_fd_sc_hd__nor2_1 _524_ (
    .A(_197_),
    .B(_200_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__clkinv_1 _525_ (
    .A(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor2_1 _526_ (
    .A(\x[1] [12]),
    .B(\x[2] [12]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__xnor2_1 _527_ (
    .A(\x[1] [12]),
    .B(\x[2] [12]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nor3_1 _528_ (
    .A(\x[1] [11]),
    .B(\x[2] [11]),
    .C(_215_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _529_ (
    .A1(\x[1] [11]),
    .A2(\x[2] [11]),
    .B1(_215_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2b_1 _530_ (
    .A_N(_216_),
    .B(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__xnor2_1 _531_ (
    .A(\x[3] [12]),
    .B(data_in[12]),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor3_1 _532_ (
    .A(\x[3] [11]),
    .B(data_in[11]),
    .C(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__o21ai_0 _533_ (
    .A1(\x[3] [11]),
    .A2(data_in[11]),
    .B1(_219_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2b_1 _534_ (
    .A_N(_220_),
    .B(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor2_1 _535_ (
    .A(_218_),
    .B(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__xor2_1 _536_ (
    .A(_218_),
    .B(_222_),
    .X(_224_)
  );
  sky130_fd_sc_hd__xnor2_1 _537_ (
    .A(_212_),
    .B(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__xnor2_1 _538_ (
    .A(_193_),
    .B(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__nand2b_1 _539_ (
    .A_N(_226_),
    .B(_211_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__xnor2_1 _540_ (
    .A(_211_),
    .B(_226_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(_204_),
    .B(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__or2_0 _542_ (
    .A(_204_),
    .B(_228_),
    .X(_230_)
  );
  sky130_fd_sc_hd__clkinv_1 _543_ (
    .A(_230_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _544_ (
    .A(_229_),
    .B(_230_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__xor2_1 _545_ (
    .A(_210_),
    .B(_232_),
    .X(sum[17])
  );
  sky130_fd_sc_hd__maj3_1 _546_ (
    .A(_193_),
    .B(_213_),
    .C(_224_),
    .X(_233_)
  );
  sky130_fd_sc_hd__clkinv_1 _547_ (
    .A(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nor2_1 _548_ (
    .A(_220_),
    .B(_223_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__clkinv_1 _549_ (
    .A(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nor2_1 _550_ (
    .A(\x[1] [13]),
    .B(\x[2] [13]),
    .Y(_237_)
  );
  sky130_fd_sc_hd__xnor2_1 _551_ (
    .A(\x[1] [13]),
    .B(\x[2] [13]),
    .Y(_238_)
  );
  sky130_fd_sc_hd__xor2_1 _552_ (
    .A(_214_),
    .B(_238_),
    .X(_239_)
  );
  sky130_fd_sc_hd__xnor2_1 _553_ (
    .A(\x[3] [13]),
    .B(data_in[13]),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nor3_1 _554_ (
    .A(\x[3] [12]),
    .B(data_in[12]),
    .C(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__o21ai_0 _555_ (
    .A1(\x[3] [12]),
    .A2(data_in[12]),
    .B1(_240_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand2b_1 _556_ (
    .A_N(_241_),
    .B(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nor2_1 _557_ (
    .A(_239_),
    .B(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__xor2_1 _558_ (
    .A(_239_),
    .B(_243_),
    .X(_245_)
  );
  sky130_fd_sc_hd__xnor2_1 _559_ (
    .A(_235_),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__xnor2_1 _560_ (
    .A(_216_),
    .B(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__xor2_1 _561_ (
    .A(_233_),
    .B(_247_),
    .X(_248_)
  );
  sky130_fd_sc_hd__nor2_1 _562_ (
    .A(_227_),
    .B(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__xnor2_1 _563_ (
    .A(_227_),
    .B(_248_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__o21ai_0 _564_ (
    .A1(_210_),
    .A2(_232_),
    .B1(_229_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a211oi_1 _565_ (
    .A1(_210_),
    .A2(_229_),
    .B1(_231_),
    .C1(_250_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__xnor2_1 _566_ (
    .A(_250_),
    .B(_251_),
    .Y(sum[18])
  );
  sky130_fd_sc_hd__nor2_1 _567_ (
    .A(_249_),
    .B(_252_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__maj3_1 _568_ (
    .A(_216_),
    .B(_236_),
    .C(_245_),
    .X(_254_)
  );
  sky130_fd_sc_hd__nor2_1 _569_ (
    .A(_241_),
    .B(_244_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor2_1 _570_ (
    .A(\x[1] [14]),
    .B(\x[2] [14]),
    .Y(_256_)
  );
  sky130_fd_sc_hd__xnor2_1 _571_ (
    .A(\x[1] [14]),
    .B(\x[2] [14]),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor3_1 _572_ (
    .A(\x[1] [13]),
    .B(\x[2] [13]),
    .C(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__xor2_1 _573_ (
    .A(_237_),
    .B(_257_),
    .X(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _574_ (
    .A(\x[3] [14]),
    .B(data_in[14]),
    .Y(_260_)
  );
  sky130_fd_sc_hd__xnor2_1 _575_ (
    .A(\x[3] [14]),
    .B(data_in[14]),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor3_1 _576_ (
    .A(\x[3] [13]),
    .B(data_in[13]),
    .C(_261_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__o21ai_0 _577_ (
    .A1(\x[3] [13]),
    .A2(data_in[13]),
    .B1(_261_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nand2b_1 _578_ (
    .A_N(_262_),
    .B(_263_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor2_1 _579_ (
    .A(_259_),
    .B(_264_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__xor2_1 _580_ (
    .A(_259_),
    .B(_264_),
    .X(_266_)
  );
  sky130_fd_sc_hd__nand2b_1 _581_ (
    .A_N(_255_),
    .B(_266_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__xor2_1 _582_ (
    .A(_255_),
    .B(_266_),
    .X(_268_)
  );
  sky130_fd_sc_hd__o31ai_1 _583_ (
    .A1(\x[1] [12]),
    .A2(\x[2] [12]),
    .A3(_238_),
    .B1(_268_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__or4_1 _584_ (
    .A(\x[1] [12]),
    .B(\x[2] [12]),
    .C(_238_),
    .D(_268_),
    .X(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _585_ (
    .A(_269_),
    .B(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nor2b_1 _586_ (
    .A(_271_),
    .B_N(_254_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__xor2_1 _587_ (
    .A(_254_),
    .B(_271_),
    .X(_273_)
  );
  sky130_fd_sc_hd__o21ai_0 _588_ (
    .A1(_234_),
    .A2(_247_),
    .B1(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__or3_1 _589_ (
    .A(_234_),
    .B(_247_),
    .C(_273_),
    .X(_275_)
  );
  sky130_fd_sc_hd__clkinv_1 _590_ (
    .A(_275_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _591_ (
    .A(_274_),
    .B(_275_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__xor2_1 _592_ (
    .A(_253_),
    .B(_277_),
    .X(sum[19])
  );
  sky130_fd_sc_hd__nand2_1 _593_ (
    .A(_267_),
    .B(_270_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nor2_1 _594_ (
    .A(_262_),
    .B(_265_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__xor2_1 _595_ (
    .A(\x[1] [15]),
    .B(\x[2] [15]),
    .X(_280_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(_256_),
    .B(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__xnor2_1 _597_ (
    .A(_256_),
    .B(_280_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__xor2_1 _598_ (
    .A(\x[3] [15]),
    .B(data_in[15]),
    .X(_283_)
  );
  sky130_fd_sc_hd__nor2_1 _599_ (
    .A(_260_),
    .B(_283_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _600_ (
    .A(_260_),
    .B(_283_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__nor2b_1 _601_ (
    .A(_284_),
    .B_N(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__xnor2_1 _602_ (
    .A(_282_),
    .B(_286_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__o21ai_0 _603_ (
    .A1(_262_),
    .A2(_265_),
    .B1(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__xnor2_1 _604_ (
    .A(_279_),
    .B(_287_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__nand2_1 _605_ (
    .A(_258_),
    .B(_289_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__xnor2_1 _606_ (
    .A(_258_),
    .B(_289_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__a21oi_1 _607_ (
    .A1(_267_),
    .A2(_270_),
    .B1(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__xor2_1 _608_ (
    .A(_278_),
    .B(_291_),
    .X(_293_)
  );
  sky130_fd_sc_hd__nor3b_1 _609_ (
    .A(_271_),
    .B(_293_),
    .C_N(_254_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__clkinv_1 _610_ (
    .A(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__xnor2_1 _611_ (
    .A(_272_),
    .B(_293_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__o31ai_1 _612_ (
    .A1(_249_),
    .A2(_252_),
    .A3(_276_),
    .B1(_274_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__o311ai_0 _613_ (
    .A1(_249_),
    .A2(_252_),
    .A3(_276_),
    .B1(_296_),
    .C1(_274_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__xnor2_1 _614_ (
    .A(_296_),
    .B(_297_),
    .Y(sum[20])
  );
  sky130_fd_sc_hd__nand2_1 _615_ (
    .A(_295_),
    .B(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__nand2_1 _616_ (
    .A(_288_),
    .B(_290_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__o21ai_0 _617_ (
    .A1(_282_),
    .A2(_284_),
    .B1(_285_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__a22oi_1 _618_ (
    .A1(\x[3] [15]),
    .A2(data_in[15]),
    .B1(\x[1] [15]),
    .B2(\x[2] [15]),
    .Y(_302_)
  );
  sky130_fd_sc_hd__and4_1 _619_ (
    .A(\x[3] [15]),
    .B(data_in[15]),
    .C(\x[1] [15]),
    .D(\x[2] [15]),
    .X(_303_)
  );
  sky130_fd_sc_hd__nor2_1 _620_ (
    .A(_302_),
    .B(_303_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__xnor2_1 _621_ (
    .A(_301_),
    .B(_304_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__xnor2_1 _622_ (
    .A(_281_),
    .B(_305_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nand2b_1 _623_ (
    .A_N(_306_),
    .B(_300_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__xor2_1 _624_ (
    .A(_300_),
    .B(_306_),
    .X(_308_)
  );
  sky130_fd_sc_hd__nor3b_1 _625_ (
    .A(_291_),
    .B(_308_),
    .C_N(_278_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__clkinv_1 _626_ (
    .A(_309_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__nor2b_1 _627_ (
    .A(_292_),
    .B_N(_308_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__nor2_1 _628_ (
    .A(_309_),
    .B(_311_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__xor2_1 _629_ (
    .A(_299_),
    .B(_312_),
    .X(sum[21])
  );
  sky130_fd_sc_hd__a31oi_1 _630_ (
    .A1(_295_),
    .A2(_298_),
    .A3(_310_),
    .B1(_311_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__a21oi_1 _631_ (
    .A1(_301_),
    .A2(_304_),
    .B1(_303_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__o211ai_1 _632_ (
    .A1(_281_),
    .A2(_305_),
    .B1(_307_),
    .C1(_314_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__xnor2_1 _633_ (
    .A(_313_),
    .B(_315_),
    .Y(sum[22])
  );
  sky130_fd_sc_hd__xnor2_1 _634_ (
    .A(_039_),
    .B(_050_),
    .Y(sum[8])
  );
  sky130_fd_sc_hd__clkinv_1 _635_ (
    .A(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _636_ (
    .A(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _637_ (
    .A(reset),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _638_ (
    .A(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _639_ (
    .A(reset),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _640_ (
    .A(reset),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _641_ (
    .A(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _642_ (
    .A(reset),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _643_ (
    .A(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _644_ (
    .A(reset),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _645_ (
    .A(reset),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _646_ (
    .A(reset),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _647_ (
    .A(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _648_ (
    .A(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _649_ (
    .A(reset),
    .Y(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _650_ (
    .CLK(clk),
    .D(sum[7]),
    .Q(data_out[0]),
    .RESET_B(_000_)
  );
  sky130_fd_sc_hd__dfrtp_1 _651_ (
    .CLK(clk),
    .D(sum[8]),
    .Q(data_out[1]),
    .RESET_B(_001_)
  );
  sky130_fd_sc_hd__dfrtp_1 _652_ (
    .CLK(clk),
    .D(sum[9]),
    .Q(data_out[2]),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _653_ (
    .CLK(clk),
    .D(sum[10]),
    .Q(data_out[3]),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_1 _654_ (
    .CLK(clk),
    .D(sum[11]),
    .Q(data_out[4]),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _655_ (
    .CLK(clk),
    .D(sum[12]),
    .Q(data_out[5]),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_1 _656_ (
    .CLK(clk),
    .D(sum[13]),
    .Q(data_out[6]),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_1 _657_ (
    .CLK(clk),
    .D(sum[14]),
    .Q(data_out[7]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _658_ (
    .CLK(clk),
    .D(sum[15]),
    .Q(data_out[8]),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _659_ (
    .CLK(clk),
    .D(sum[16]),
    .Q(data_out[9]),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _660_ (
    .CLK(clk),
    .D(sum[17]),
    .Q(data_out[10]),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfrtp_1 _661_ (
    .CLK(clk),
    .D(sum[18]),
    .Q(data_out[11]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _662_ (
    .CLK(clk),
    .D(sum[19]),
    .Q(data_out[12]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _663_ (
    .CLK(clk),
    .D(sum[20]),
    .Q(data_out[13]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _664_ (
    .CLK(clk),
    .D(sum[21]),
    .Q(data_out[14]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _665_ (
    .CLK(clk),
    .D(sum[22]),
    .Q(data_out[15]),
    .RESET_B(_015_)
  );
  \$paramod\DFF\N=16  \delay_line[1].dff_inst  (
    .clk(clk),
    .data_delayed(\x[1] ),
    .data_in(data_in),
    .reset(reset)
  );
  \$paramod\DFF\N=16  \delay_line[2].dff_inst  (
    .clk(clk),
    .data_delayed(\x[2] ),
    .data_in(\x[1] ),
    .reset(reset)
  );
  \$paramod\DFF\N=16  \delay_line[3].dff_inst  (
    .clk(clk),
    .data_delayed(\x[3] ),
    .data_in(\x[2] ),
    .reset(reset)
  );
  assign sum[4:0] = 5'h00;
endmodule
